import pytest

from tilia_core.tql import TQLError, format_error, parse

DESIGN_EXAMPLES = [
    "verse THEN chorus",
    "verse+",
    "verse?",
    "verse*",
    "verse{2}",
    "verse/chorus",
    "* IN markers WHERE time > 1:30",
    "V7[inversion = 0]",
    "PAC IN cadences DURING ST IN form",
    "ST[CONTAINS PAC IN cadences]",
    "ST[ENDS WITH PAC IN cadences]",
    "ST[continuation{2}]",
    "(verse THEN chorus)+",
    '* IN "Form (A)" SAME * IN "Form (B)" WHERE $1.label != $2.label',
    '"I:PAC" IN cadences -> SET label = "PAC"',
    "ST[continuation{2}] IN form",
    "ST[CONSISTS OF presentation THEN continuation{2}] IN form",
    "exposition[continuation] IN form",
    "exposition[CONTAINS continuation] IN form",
    "* THEN *[continuation{2}] IN form",
    "MT THEN ST[continuation{2}] IN form",
    "continuation[parent = ST] IN form",
    "ST[CONTAINS PAC IN cadences] IN form",
    "ST[ENDS WITH PAC IN cadences] IN form",
    "ST[ENDS WITH EC IN cadences] IN form",
    "* IN cadences ENDS ST IN form",
    "* IN cadences SAME END ST IN form",
    "MT[ENDS WITH HC IN cadences] THEN TR IN form",
    "TR THEN ST[CONTAINS PAC IN cadences] IN form",
    "ST IN form CONTAINS PAC IN cadences",
    "MT[STARTS WITH presentation]",
    "continuation[ENDS WITH cadential]",
    "ST[NOT continuation]",
    "ST[NOT CONTAINS PAC IN cadences]",
    "ST[continuation{2} AND CONTAINS PAC IN cadences]",
    "ST[CONTAINS HC THEN PAC IN cadences]",
    "*[CONTAINS continuation[ENDS WITH cadential]] IN form",
    "ST IN form ENDS WITH PAC IN cadences",
    "ST[ENDS WITH HC THEN PAC IN cadences]",
    "MT[STARTS WITH presentation THEN continuation]",
    "STARTS WITH intro IN form",
    "ENDS WITH bridge IN form",
    "CONSISTS OF intro THEN *+ THEN outro IN form",
    "HC IN cadences BEFORE PAC IN cadences WITHIN 8 bars",
    "solo IN ranges AFTER verse IN form WITHIN 2 bars",
    "(verse THEN chorus) OR (verse THEN bridge)",
    "[color = pink] THEN bridge",
    "bridge.sub",
    "HC THEN PAC IN cadences",
    "PAC IN cadences DURING ST IN form WHERE $1.start >= $2.start + 4 bars",
    "ST IN form STARTS AFTER MT IN form WHERE $1.start >= $2.start + 16 bars",
    "* THEN @bridge THEN * IN form",
    "* THEN @X THEN *",
    "verse+ THEN @chorus IN form",
    '* THEN @bridge THEN * IN form -> TAG "inner"',
    "chorus[start >= 50%] IN form",
    "*[start >= 33% AND end <= 67%] IN form",
    'verse+ THEN chorus IN form -> GROUP AS "A"',
    'ST[ENDS WITH PAC IN cadences] IN form -> TAG "pac-closed"',
    '* IN cadences ENDS ST IN form -> TAG "closes-st"',
    '* IN "Form (A)" SAME * IN "Form (B)" WHERE $1.label != $2.label -> TAG $0 "disagree"',
    "verse+ THEN chorus IN form",
    '"chorus?" IN form',
    "G7 THEN C IN harmony",
    "V7 THEN I IN harmony",
    "* IN form WHERE level = 2",
    "* IN harmony WHERE inversion = 1",
    "V7[inversion = 0] THEN I IN harmony",
    "V65 THEN I IN harmony",
    "[color = pink] THEN bridge IN form",
    'bridge IN form WHERE author = "Trevor de Clercq"',
    'V7[key = "c"] THEN I IN harmony WHERE file.composer = "Mozart"',
    '* IN keys WHERE key = "Eb"',
    "Transition[bar = 1..60] IN form",
    "PAC[downbeat] IN cadences",
    "*[bar = 12..16 AND pass = 2] IN form",
    "ST IN form NOT CONTAINS PAC IN cadences",
    "solo IN ranges OVERLAPS bridge IN form",
    "* IN keys SAME START ST IN form",
    '* IN "Form (A)" SAME END * IN "Form (B)"',
    "fermata IN markers SAME END * IN form",
    '* IN "Form (A)" SAME * IN "Form (B)"',
    "* IN keys CONTAINS ST IN form",
    "sentence[presentation THEN continuation] IN form",
    "TR THEN ST[continuation{2}] IN form",
    "TR THEN ST[CONSISTS OF presentation THEN continuation{2}] IN form",
    "TR[ENDS WITH HC IN cadences] THEN ST[continuation{2}] IN form",
    "MT[STARTS WITH presentation] IN form",
    "ST[NOT continuation] IN form",
    "continuation[parent = ST] IN form",
    "exposition[CONTAINS presentation] IN form",
    "ST[CONTAINS HC THEN PAC IN cadences] IN form",
    "*[continuation[ENDS WITH cadential]] IN form",
    "CONSISTS OF (verse THEN chorus){2} IN form",
    "(verse THEN chorus)+ THEN bridge IN form",
    "(verse THEN chorus) OR (verse THEN bridge) IN form",
    'WHERE tl.name ~ /^Form \\((.+)\\)$/ -> SET tl.role = "form", tl.author = "\\1"',
    '"I:PAC" IN cadences -> SET label = "PAC"',
    'verse THEN chorus WHERE author = "de Clercq"',
    "_?verse THEN chorus",
    "prechorus THEN NOT chorus",
    "chorus THEN * THEN bridge",
    "verse/SRDC OR chorus",
    "chorus / *",
    "(verse THEN prechorus?)+ THEN chorus",
    'verse+ THEN chorus IN form -> GROUP AS "A_compound"',
    'verse THEN chorus -> SET $2.label = "refrain"',
    'verse THEN chorus -> TAG "check"',
    "NOT /^_/ IN form",
]


@pytest.mark.parametrize("query", DESIGN_EXAMPLES)
def test_design_example_parses(query):
    try:
        parse(query)
    except TQLError as exc:
        pytest.fail(
            f"design example failed to parse: {query!r}\n{format_error(query, exc)}"
        )
