{
  "file_path": "C:/Users/Felipe/dev/tilia-desktop/.claude/worktrees/tilia-app-dns-fix-cb44c6/repro/harmony-roman-s.tla",
  "media_path": "",
  "media_metadata": {
    "title": "harmony-roman-s",
    "notes": "",
    "media length": 100,
    "composer": "",
    "tonality": "",
    "time signature": "",
    "performer": "",
    "performance year": "",
    "arranger": "",
    "composition year": "",
    "recording year": "",
    "form": "",
    "instrumentation": "",
    "genre": "",
    "lyrics": ""
  },
  "timelines": {
    "0": {
      "kind": "HARMONY_TIMELINE",
      "level_count": 1,
      "level_height": 35,
      "is_visible": true,
      "name": "",
      "ordinal": 1,
      "visible_level_count": 2,
      "hash": "46fa9e532d92228f5688fb04a2cc17e9",
      "components": {
        "2": {
          "time": 0.0,
          "comments": "",
          "step": 0,
          "accidental": 0,
          "quality": "major",
          "inversion": 0,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "6c48851babc6afa48936cdf65180bd61"
        },
        "3": {
          "time": 10,
          "comments": "",
          "step": 0,
          "accidental": 0,
          "quality": "major",
          "inversion": 1,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "ca8fd969194756510648e632ea0be4a0"
        },
        "4": {
          "time": 20,
          "comments": "",
          "step": 0,
          "accidental": 0,
          "quality": "major",
          "inversion": 2,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "2a58a41503d3d03fd02087b0738a5b58"
        },
        "5": {
          "time": 30,
          "comments": "",
          "step": 4,
          "accidental": 0,
          "quality": "dominant-seventh",
          "inversion": 1,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "d522cbc0c607b8b4104f947f3c10a4f4"
        },
        "6": {
          "time": 40,
          "comments": "",
          "step": 4,
          "accidental": 0,
          "quality": "dominant-seventh",
          "inversion": 2,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "631e562c66dc19c2e715d87a5aa5c22e"
        },
        "7": {
          "time": 50,
          "comments": "",
          "step": 4,
          "accidental": 0,
          "quality": "dominant-seventh",
          "inversion": 3,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "8e48290e575fc9f7b4639c44456ee5ac"
        },
        "8": {
          "time": 60,
          "comments": "",
          "step": 1,
          "accidental": 0,
          "quality": "dominant-seventh",
          "inversion": 1,
          "applied_to": 4,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "04edd729caae353bf67a23f8171093aa"
        },
        "9": {
          "time": 70,
          "comments": "",
          "step": 1,
          "accidental": 0,
          "quality": "minor-seventh",
          "inversion": 1,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "305e60532e03f546c8ff94b209d21034"
        },
        "10": {
          "time": 80,
          "comments": "",
          "step": 4,
          "accidental": 0,
          "quality": "dominant-ninth",
          "inversion": 3,
          "applied_to": 0,
          "level": 1,
          "display_mode": "roman",
          "custom_text": "",
          "custom_text_font_type": "analytic",
          "kind": "HARMONY",
          "hash": "80a5eb6f96a6ee8e7df1f803e73978ad"
        },
        "1": {
          "time": 0.0,
          "step": 0,
          "accidental": 0,
          "type": "major",
          "comments": "",
          "level": 2,
          "kind": "MODE",
          "hash": "93165266d353cdc0a4b8df96d5d0f91d"
        }
      },
      "components_hash": "1e052a4bd06b7a723f32d01cea45ea1f"
    }
  },
  "timelines_hash": "0f9df940ab670331652bf4d39914e000",
  "app_name": "TiLiA",
  "version": "0.6.4"
}
