name: Build test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with pyinstaller
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        TARGET: [windows]
        CMD_BUILD: [pyinstaller tilia.spec]
        OUT_FILE_NAME: [tilia-0.5.1-win.exe]
        ASSET_MIME: [application/vnd.microsoft.portable-executable]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: 'x64'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with pyinstaller for ${{matrix.TARGET}}
        shell: bash
        run: ${{matrix.CMD_BUILD}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.OUT_FILE_NAME}}
          path: dist/${{matrix.OUT_FILE_NAME}}
